version: '3.8'

services:
  led-controller:
    build: .
    ports:
      - "5000:5000"
    privileged: true
    volumes:
      - .:/app
    command: ["python", "led_controller.py"]
    restart: unless-stopped



